Handling when raw_data is None
This happens on some occasions when geolocate IP couldn't find the IP's location

Error log:
```
backend_1      |  [2021-03-24 11:20:45,391] root         ERROR    Couldn't geolocate ip (middleware 1 140405557767496)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 26, in process_request
backend_1      |     self._get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 61, in _get_geolocation
backend_1      |     self._geolocation_data = get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/utils.py", line 52, in get_geolocation
backend_1      |     return backend_instance.data()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/base.py", line 33, in data
backend_1      |     self._parse()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/ipdataco.py", line 26, in _parse
backend_1      |     self._continent = self._raw_data.get('continent_name')
backend_1      | AttributeError: 'NoneType' object has no attribute 'get'
backend_1      | [2021-03-24 11:20:45,533] root         ERROR    Couldn't geolocate ip (middleware 1 140405557767496)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 42, in process_response
backend_1      |     self._get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 61, in _get_geolocation
backend_1      |     self._geolocation_data = get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/utils.py", line 52, in get_geolocation
backend_1      |     return backend_instance.data()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/base.py", line 33, in data
backend_1      |     self._parse()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/ipdataco.py", line 26, in _parse
backend_1      |     self._continent = self._raw_data.get('continent_name')
backend_1      | AttributeError: 'NoneType' object has no attribute 'get'
```